target-version = "py311"
line-length = 100

[lint]
select = ["ALL"]
ignore = [
    "A001",
    "A002",
    "ANN401",
    "BLE001",
    "C901",
    "COM812",
    "D",
    "ISC001",
    "PLR0912",
    "PLR0913",
    "S",
]
